trigger:
- master

variables:
  PUBLIC_REPO_URL: 'git@github.com:ProtonVPN/win-tap-adapter.git'

jobs:
- job: BuildTAPAdapter
  pool:
    vmImage: 'windows-latest'
  steps:
  - checkout: git://github.com/OpenVPN/tap-windows6.git
  - powershell: |
      (Get-Content version.m4) -replace "(\[PRODUCT_TAP_WIN_COMPONENT_ID]\, \[)([a-z0-9]+)(\])", 'tapprotonvpn' | Out-File version.m4 -Encoding "UTF8"
      (Get-Content version.m4) -replace "(\[PRODUCT_TAP_WIN_PROVIDER]\, \[)([a-zA-Z0-9- ]+)(\])", 'TAP-ProtonVPN Windows Provider V9' | Out-File version.m4 -Encoding "UTF8"
      (Get-Content version.m4) -replace "(\[PRODUCT_TAP_WIN_DEVICE_DESCRIPTION]\, \[)([a-zA-Z0-9- ]+)(\])", 'TAP-ProtonVPN Windows Adapter V9' | Out-File version.m4 -Encoding "UTF8"
    displayName: 'Modify version.m4'
  - script: python buildtap.py --sdk=wdk -b
    displayName: 'Build TAP'
  - publish: tap-windows6/dist
    artifact: tap-windows6
    displayName: 'Publish Artifacts'